//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class List
    {

        public int id { get; set; }

        [DisplayName("TMDB ID")]
        [Required(ErrorMessage = "This Field is Required")]
        public Nullable<int> tmdb_id { get; set; }

        [DisplayName("Title")]
        [Required(ErrorMessage = "This Field is Required")]
        public string title { get; set; }

        [DisplayName("Year")]
        [Required(ErrorMessage = "This Field is Required")]
        public string year { get; set; }

        [DisplayName("Quality")]
        [Required(ErrorMessage = "This Field is Required")]
        public string quality { get; set; }

        [DisplayName("Type")]
        public string type { get; set; }

        [DisplayName("Genre")]
        public string genre { get; set; }

        [DisplayName("Poster Link")]
        public string poster { get; set; }

        [DisplayName("Trailer Link")]
        public string trailer { get; set; }
    }
}
